//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSDH.web.Application.Con_lau_moi_tim_duoc_trang_admin_cua_a_nha
{


    public partial class index
    {
    }
}
